### ISSUE TITLE
Can't execute bun build bundle

### ISSUE THREAD

**Issue by DrUse1** [kitajs/html#32]
When running the bun bundler. I get this error : 
```
$ bun run ./build/index.js
24813 | // node_modules/@kitajs/html/index.js
24814 | var require_html = __commonJS((exports, module) => {
24815 |   __export(exports, {
24816 |     toKebabCase: () => {
24817 |       {
24818 |         return $toKebabCase;
                   ^
ReferenceError: Can't find variable: $toKebabCase
      at toKebabCase (/Users/mohamed/Desktop/htmx/build/index.js:24818:15)
      at /Users/mohamed/Desktop/htmx/build/index.js:25160:20
      at /Users/mohamed/Desktop/htmx/build/index.js:36:71
      at /Users/mohamed/Desktop/htmx/build/index.js:27554:11
```

I don't know if it's a bun issue or a kitajs/html issue.

Here's the github repo : https://github.com/DrUse1/htmx

You can reproduce the error by cloning the repo and doing this command :
```
bun install | bun run build | bun run prod
```

**Comment by arthurfiorette** [comment]
https://github.com/oven-sh/bun/issues/5654

**Comment by arthurfiorette** [comment]
Next kitajs/html version removes the line that generates the error. This way we don't need to wait until bun fixes the issue.
